---
- name: configure | make sure php dependencies are installed/up-to-date
  sudo: yes
  apt: pkg={{item}}
  with_items:
    - php5-mcrypt
    - php5-mysql
    - php5-curl
    - php5-gd
    - unzip

- name: configure | enable mcrypt module
  command: "php5enmod mcrypt"

- name: configure | get release
  get_url:
    url: "https://www.prestashop.com/ajax/controller.php?method=download&type=releases&file=prestashop_{{ prestashop_version }}.zip&language=en"
    dest: /var/www/prestashop.zip

- name: configure | unzip release
  command: "unzip prestashop.zip"
  args:
    chdir: /var/www
    creates: prestashop

- name: configure | remove release zip and install html
  file:
    name: "/var/www/{{item}}"
    state: absent
  with_items:
    - Install_PrestaShop.html
    - prestashop.zip

- name: configure | set permissions
  file:
    path: /var/www
    mode: 0777
    recurse: yes
    state: directory
    owner: www-data
    group: www-data
